config/routes.rb
Rails.application.routes.draw do
  
  resources :users do 
    resources :songs 
  end

  resources :songs do
    resources :song_chords
  end

   resources :songs 
  #   resources :progressions
  # end
    
  root 'static_pages#home'

  resources :chords
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chord.rb
class Chord < ApplicationRecord
  has_many    :song_chords
  has_many    :songs, through: :song_chords
end

app/models/chord_progressions.rb
class ChordProgression < ApplicationRecord
  belongs_to :chord
  belongs_to :song
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :song
  
  validates  :content, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_many   :song_chords
  has_many   :chords, through: :song_chords
  validates  :artist, presence: true
  validates  :title,  presence: true
end

app/models/song_chord.rb
class SongChord < ApplicationRecord
  belongs_to :chord
  belongs_to :song

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many  :songs
  # has_many  :comments, through:   :songs
  
  # validates :name,     presence:   true
  # validates :name,     uniqueness: true
  # validates :email,    presence:   true
  # validates :email,    uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def login_user
    unless logged_in?
      redirect_to login_path
    end
  end

  def song_belongs_to_user?
    current_user.id == @song.user_id
  end

  def set_song
    @song = Song.find_by(id: params[:id])
  end

  def current_song
    @song = Song.find_by(id: params[:song_id])
  end
  
  helper_method :song_belongs_to_user?
  helper_method :current_user
  helper_method :current_song
  helper_method :logged_in?
  helper_method :login_user
  helper_method :set_song
  
end

app/controllers/chords_controller.rb
class ChordsController < ApplicationController
  before_action :set_song
  before_action :set_chord, only: [:show, :edit, :update, :destroy]
  before_action :verify_user

  def index 
    @chord = @song.chords.all
  end

  def show
  end

  def new
    @chord = @song.chords.new
  end

  def create
    @chord = @song.chords.create(chord_params)
    if @chord.save
      redirect_to song_path(@song)
    else
      redirect_to root
    end
  end

  def edit
  end

  def update
  end

  private

  def set_song
    @song = Song.find_by(params[:song_id])
  end

  def set_chord
    @chord = Chord.find(params[:id])
  end

  def chord_params
    params.require(:chord).permit(:name, :pattern, :song_id)
  end

  def verify_user
    redirect_to song_path(@song) if @song.user != current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :login_user, except: [:show, :index]
  before_action :verify_song_user, only: [:edit, :update, :destroy]

  def new 
    @song = Song.new
    @chords = Chord.all
  end

  def index
    @songs = Song.all
  end

  def create
    # raise params
    @song = Song.new(song_params)
    @song.user = current_user
    if @song.save
      redirect_to song_path(@song)
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @chords = Chord.all
  end

  def update
    # raise params.inspect
    if @song.update(song_params)
      redirect_to song_path(@song)
    elsif @song.song_chords.update
      redirect_to song_path(@song)
    else
      redirect to edit_song_path
    end
  end

  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), 
        notice: 'song was successfully destroyed.' }
      end
  end

  private

  def song_params
    params.require(:song).permit(
      :title, 
      :artist, 
      :key,
      :tuning,
      :difficulty,
      :capo,
      :lyrics,
      :user_id,
      chord_ids:[],
      chords_attributes:[:name, :img]
      )
  end

  def verify_song_user
    redirect_to user_path(current_user) if @song.user != current_user
  end

  def verify_song
    redirect_to user_path(current_user) if @song.user != current_user
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @songs = Song.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email, 
      :password,
      :password_confirmation
      )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chords_helper.rb
module ChordsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/song_chord_helper.rb
module SongChordsHelper
end

app/helpers/song_chords_helper.rb
module SongChordsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chords/_form.html.erb
<%= form_for @chord do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :pattern %>
  <%= f.text_field :pattern %>
  <br />

  <%= f.submit %>
<% end %>

app/views/chords/edit.html.erb
<h1>Edit Chords</h1>
<%= render partial: "form" %>

app/views/chords/new.html.erb
<h1>Add Chords</h1>
<%= render partial: "form" %>

<div class="card" style="width: 18rem;">
  <%= image_tag ("c_chord.png"), class: "img-responsive", style: "width: 200px; height: 200px" %>
  <div class="card-body">
    <a href="#" class="btn btn-primary">Add Chord</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <%= image_tag ("d_chord.png"), class: "img-responsive", style: "width: 200px; height: 200px" %>
  <div class="card-body">
    <a href="#" class="btn btn-primary">Add Chord</a>
  </div>
</div>

<%= image_tag ("c_chord.png"), class: "img-responsive", style: "width: 200px; height: 200px" %>
<%= image_tag ("d_chord.png"), class: "img-responsive", style: "width: 200px; height: 200px" %>
<%= image_tag ("e_chord.png"), class: "img-responsive", style: "width: 200px; height: 200px" %>
<%= image_tag ("f_chord.png"), class: "img-responsive", style: "width: 200px; height: 200px" %>
<%= image_tag ("g_chord.png"), class: "img-responsive", style: "width: 200px; height: 200px" %>
<%= image_tag ("a_chord.png"), class: "img-responsive", style: "width: 200px; height: 200px" %>
<%= image_tag ("b_chord.png"), class: "img-responsive", style: "width: 200px; height: 200px" %>

app/views/songs/_chords.html.erb
<nav class="navbar navbar-light" style="background-color: #c0c0c0;">
  <span class="pull-left">
  <h3 class="display-4">Chords</h3>
    <% @song.chords.each do |chord| %>
      <div class="chord">
        <strong><%= chord.name %></strong> 
      </div>
      <div class="chord">
        <%= chord.pattern %><br>
      </div>
    <% end %>
  </span>
</nav>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
  <div class="form-row">
    <div class="form-group col-md-5">
      <%= f.label :artist %>
      <%= f.text_field :artist, class:'form-control', placeholder:"Beatles" %>
    </div>
    <div class="form-group col-md-7">
      <%= f.label :title %>
      <%= f.text_field :title, class:'form-control', placeholder:"Daytripper" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-3">
      <%= f.label :tuning %>
      <%= f.text_field :tuning, class:'form-control', placeholder:"(select)" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :key %>
      <%= f.text_field :key, class:'form-control', placeholder:"(select)" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :difficulty %>
      <%= f.text_field :difficulty, class:'form-control', placeholder:"(select)" %>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :capo %>
      <%= f.text_field :capo, class:'form-control', placeholder:"(select)" %>
    </div>
  </div>

  <div class="form-group col-lg-8">
    <div class="form-group">
      <%= f.label :lyrics %>
      <%= f.text_area :lyrics, :rows => "10", class:'form-control', placeholder:"Enter Lyrics" %>
    </div>
  </div>

  <div class="form-group col-lg-8">
    <div class="form-group">
    <%= f.label :chords, "Chords Used" %><br>
    <%= hidden_field_tag "song[chord_ids][]", nil %>
    <% @chords.each do |chord|%>
        <%= check_box_tag "song[chord_ids][]", chord.id, @song.chord_ids.include?(chord.id)%>
        <%= image_tag("#{chord.img}", size: "200x200") %>
    <% end %>
    <br>
    
  <div class="form row">
    <div class="col-sm-10">
      <%= f.submit 'Submit', class: 'btn-primary btn-lg'  %>
    </div>
  </div>
<% end %>

app/views/songs/_jumbonav.html.erb
<nav class="navbar navbar-light" style="background-color: #c0c0c0;">
  <span class="pull-right">
    <div class="btn btn-warning">
      <%= link_to "Edit Song", edit_user_song_path(current_user, @song) %>
    </div>
  </span>
</nav>
<% if @song.chords != nil %>
<nav class="navbar navbar-light" style="background-color: #c0c0c0;">
  <h2> Chord Progression </h2>
  <span class="center">
    <% @song.chords.all.each do |chord| %>
      <%= image_tag("#{chord.img}", size: "200x200") %>
<% end %>
  </span>
  </nav>
<% end %>

app/views/songs/_song.html.erb
<div class="jumbotron text-center">

  <% if current_user %>
    <% if song_belongs_to_user? %>
      <%= render "jumbonav" %>

    <% end %>
  <% end %>
  
  <h1 class="display-4"><%= @song.title %></h1>
  <h2 class="display-4">by <%= @song.artist %></h2>
  <h4 class="display-4">Song Added by: 
    <%= @song.user.name %> 
  </h4>
  
  <div class="form-row">
    <div class="container-group col-md-3">
      <h2 class="display-2">Key</h2>
      <p><%= @song.key %></p>
    </div>
    <div class="container-group col-md-3">
      <h2 class="display-2">Tuning</h2>
      <p><%= @song.tuning %></p>
    </div>
    <div class="container-group col-md-3">
      <h2 class="display-2">Difficulty</h2>
      <p><%= @song.difficulty %></p>
    </div>
    <div class="container-group col-md-3">
      <h2 class="display-2">Capo</h2>
      <p><%= @song.capo %></p>
    </div>
  </div>
  
  
  <p class="text-left"><%= simple_format(@song.lyrics) %></p>

</div>

app/views/songs/edit.html.erb
<%= render "form" %>

app/views/songs/index.html.erb
<h2>Current Songs</h2>
<% @songs.each do |song| %>
  <div><%= link_to song.title, song_path(song) %></div>
<% end %>

app/views/songs/new.html.erb
<h2>Create a new song</h2>


<%= render "form" %>

app/views/songs/show.html.erb
<%= render "song" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

  <p> Already have an account? <%= link_to "Login", "/login"%> here or sign up with #FACEBOOK</p>
</div>

app/views/users/show.html.erb
<strong>Welcome Back!</strong> <%= current_user.name %>

<div>
  <h3 class="text-center" >Your Songs</h3><br>
  <div class="d-flex card-group text-center">  
    <% current_user.songs.each do |song| %>
  
      <div class="card">
      <%# <img class="card-img-top" src=".../100px200/" alt="Card image cap"> %>
      <div class="card-body">
        <h5 class="card-title"><%= song.title %> by <%= song.artist %></h5>
          <div class="btn-group" role="group" aria-label="Basic example">
            <button type="button" class="btn btn-secondary"><%= link_to "View", song_path(song) %></button>
            <button type="button" class="btn btn-secondary"><%= link_to "Edit", edit_user_song_path(@user, song) %></button>
            <button type="button" class="btn btn-secondary"><%= link_to "Delete", song_path(song), 
            data: {confirm: "Are you sure?"}, :method => :delete %> </button>
          </div>
      </div>

      <div class="card-footer">
        <small class="text-muted">
          <strong><%= song.tuning %></strong> Tuning
          <strong><%= song.difficulty %></strong> Level
        </small>
      </div>

      </div><br>
 
  <% end %>
  </div>