config/routes.rb
Rails.application.routes.draw do
  
  resources :users do 
    resources :songs 
  end

  resources :songs do
    resources :song_chords
  end

   resources :songs 
  #   resources :progressions
  # end
    
  root 'static_pages#home'

  resources :chords
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chord.rb
class Chord < ApplicationRecord
  has_many    :song_chords
  has_many    :songs, through: :song_chords
end

app/models/chord_progressions.rb
class ChordProgression < ApplicationRecord
  belongs_to :chord
  belongs_to :song
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :song
  
  validates  :content, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_many   :song_chords
  has_many   :chords, through: :song_chords
  validates  :artist, presence: true
  validates  :title,  presence: true
end

app/models/song_chord.rb
class SongChord < ApplicationRecord
  belongs_to :chord
  belongs_to :song

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many  :songs
  # has_many  :comments, through:   :songs
  
  # validates :name,     presence:   true
  # validates :name,     uniqueness: true
  # validates :email,    presence:   true
  # validates :email,    uniqueness: true
end

app/controllers/chords_controller.rb
class ChordsController < ApplicationController
  before_action :set_song
  before_action :set_chord, only: [:show, :edit, :update, :destroy]
  before_action :verify_user

  def index 
    @chord = @song.chords.all
  end

  def show
  end

  def new
    @chord = @song.chords.new
  end

  def create
    @chord = @song.chords.create(chord_params)
    if @chord.save
      redirect_to song_path(@song)
    else
      redirect_to root
    end
  end

  def edit
  end

  def update
  end

  private

  def set_song
    @song = Song.find_by(params[:song_id])
  end

  def set_chord
    @chord = Chord.find(params[:id])
  end

  def chord_params
    params.require(:chord).permit(:name, :pattern, :song_id)
  end

  def verify_user
    redirect_to song_path(@song) if @song.user != current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :login_user, except: [:show, :index]
  before_action :verify_song_user, only: [:edit, :update, :destroy]

  def new 
    @song = Song.new
    @chords = Chord.all
  end

  def index
    @songs = Song.all
  end

  def create
    # raise params
    @song = Song.new(song_params)
    @song.user = current_user
    if @song.save
      redirect_to song_path(@song)
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @chords = Chord.all
  end

  def update
    # raise params.inspect
    if @song.update(song_params)
      redirect_to song_path(@song)
    elsif @song.song_chords.update
      redirect_to song_path(@song)
    else
      redirect to edit_song_path
    end
  end

  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), 
        notice: 'song was successfully destroyed.' }
      end
  end

  private

  def song_params
    params.require(:song).permit(
      :title, 
      :artist, 
      :key,
      :tuning,
      :difficulty,
      :capo,
      :lyrics,
      :user_id,
      chord_ids:[],
      chords_attributes:[:name, :img]
      )
  end

  def verify_song_user
    redirect_to user_path(current_user) if @song.user != current_user
  end

  def verify_song
    redirect_to user_path(current_user) if @song.user != current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email, 
      :password,
      :password_confirmation
      )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chords_helper.rb
module ChordsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/song_chord_helper.rb
module SongChordsHelper
end

app/helpers/song_chords_helper.rb
module SongChordsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cittearn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <header class="navbar navbar-default" role="navigation">
    <div class="navbar">
      <div class="container">
        <div id="logo" class="navbar-brand">
          <%= link_to "Cittearn", root_path %>
        </div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav navbar-left">
						<li><%= link_to 'All Songs', songs_path %></li>
									
            <% if logged_in? %>

            	<li><%= link_to 'New Song', new_user_song_path(current_user) %></li>
              </ul>

              <ul class="nav navbar-nav pull-right">
                <li><%= link_to 'My Account', user_path(current_user) %></li>  
                <li><%= link_to 'Logout', logout_path %></li>
              </ul>
              
            <% else %>
              </ul>
              <ul class="nav navbar-nav pull-right">
                <li><%= link_to "Sign Up", signup_path %></li>
                <li><%= link_to "Log In", login_path %></li>
              </ul>

            <% end %>
				</nav>
      </div>
    </div>
  </header>
  
  <body>
    <%= yield %>
  </body>
</html>